version: "2"
services:
  db:
    image: postgres:9.5.5
    environment:
      - POSTGRES_USER=glitchr
      - POSTGRES_PASSWORD=password
  web:
    build: .
    depends_on:
      - db
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://glitchr:password@db/glitchr
